name: Update Gist
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: heydayle/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 99e6b6e84082c71ecd5754c090874c5c
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
